### ISSUE TITLE
Error Callback

### ISSUE THREAD

**Issue by BulgaRpl** [VORPCORE/VORP-Fishing#1]
![image](https://user-images.githubusercontent.com/69915160/95912501-28300c80-0da3-11eb-898e-1a819db4560f.png)

**Comment by BulgaRpl** [comment]
Another issue is that The bait is not removed from eq after use, Its like infinity.

**Comment by Artzalez** [comment]
Fixed https://github.com/VORPCORE/VORP-Fishing/commit/5b81424c8ace78fd7663cf3d2ab1a47e3a975e90
Redownload from Releases
